### ISSUE TITLE
No GUI shows up in the JS version

### ISSUE THREAD

**Issue by datadata95** [m13253/sb-jsfx-plugins#2]
Hi, wont get any GUI showing up in the JS version of the plugin. It's just blank.

**Comment by m13253** [comment]
Check if you have latest version of REAPER.

Also, please report your environment (software versions, operating system, …)

**Comment by datadata95** [comment]
I'm using the latest version of Reaper on a Macbook Pro with Mac OS 10.14.6 Mojave
<img width="644" alt="Skärmavbild 2022-04-09 kl  16 12 49" src="https://user-images.githubusercontent.com/69867381/162577999-7b72c004-b07f-4b42-bba4-4feb995dead3.png">
Looks like this when I've placed the plugin on a track.

EDIT: Solved it now by copying all the text from the jsfx file here on Github instead of using what I got when I downloaded the zip file from here.

**Comment by m13253** [comment]
Thanks for the new information.

If it is solved, please close this issue.
